Truncate SES message data to CloudWatch
humanmade/altis-cloud pull request #374
Opened 2021-04-21 05:21 UTC by ivankristianto

Fixes: #371 

This PR is similar with the PR I made in https://github.com/humanmade/aws-xray/pull/77
With solve the same issue where the data send to cloudwatch could be more than 64Kb and thus we cannot see the email log if the email has attachment.

For logging purpose we don't need to store email attachment in the cloudwatch, it's enough information to see if the email header and delivery status.

So this PR truncate the message down.
Let me know what you think? @rmccue @roborourke @joehoyle

2021-04-21 08:05 UTC, joehoyle requested changes

2021-04-21 08:05 UTC, joehoyle commented on inc/ses_to_cloudwatch/namespace.php
> +	if ( mb_strlen( $message ) < $max_size ) {
If you are counting length to be a proxy for size, this should be `strlen` not `mb_strlen`. A string that is `mb_strlen` of 1 can be a size of 3bytes for example.

2021-04-21 08:07 UTC, joehoyle commented on inc/ses_to_cloudwatch/namespace.php
> +function truncate_message( string $message, int $max_size = 5 * 1024, string $replacement = '…' ) : string {
This seems maybe `truncate_string` is more appropriate, as from the perspective of this function, it doesn't need to be a "message"

2021-04-22 09:27 UTC, joehoyle approved these changes

2021-04-22 09:27 UTC, joehoyle commented
Handing off to @roborourke for final review

2021-04-22 10:36 UTC, roborourke approved these changes

2021-04-22 10:36 UTC, roborourke commented on inc/ses_to_cloudwatch/namespace.php
> + * @param string $replacement String replacement.
We don't align docblock params any more, just prevents unnecessary code changes when adding / changing a parameter in future.
```suggestion
 * @param string $string String to truncate.
 * @param int $max_size Maximum size in bytes, default 5KB.
 * @param string $replacement String replacement.
```

2021-04-22 10:36 UTC, roborourke commented on inc/ses_to_cloudwatch/namespace.php
> +	return substr_replace( $string, $replacement, $max_size / 2, strlen( $string ) - $max_size + strlen( $replacement ) );
Took me a while to grok what this is doing! Nice work

2021-04-22 10:36 UTC, merged