Add docs for all missing Cloud config options
humanmade/altis-cloud pull request #452
Opened 2021-08-31 14:03 UTC by roborourke

Extends the documentation to cover all cloud module features and integrations including relevant documentation of config and APIs.

Fixes #209

2021-09-01 14:05 UTC, shadyvb requested changes
LGTM, left some minor suggestions..

2021-09-01 15:25 UTC, roborourke commented on docs/read-replica-database.md
> +Altis uses multiple instances of the database to improve performance and resilience. The read replica set up uses a read only copy of the database for all `SELECT` queries and another copy to handle
Yeah technically, good shout

2021-09-01 15:27 UTC, roborourke commented
Nice one @shadyvb, committed those

2021-09-13 09:29 UTC, shadyvb approved these changes

2021-09-13 09:29 UTC, merged