URL encode filenames in CDN Media Purge
humanmade/altis-cloud pull request #841
Opened 2024-02-05 15:30 UTC by joehoyle

CloudFront will return an error from `createInvalidation` if the URL is not encoded. `tachyon_url()` already does this internally, so is not an issue on the tachyon_url.

2024-02-05 15:56 UTC, mikelittle approved these changes
Looks good, thanks Joe, but the first linter issue (extra space) could be fixed.

2024-02-05 15:58 UTC, kovshenin approved these changes

2024-02-06 07:53 UTC, jerico approved these changes

2024-02-07 18:26 UTC, rmccue requested changes

2024-02-07 18:26 UTC, rmccue commented on inc/cloudfront_media_purge/namespace.php
> +	$items[]          = $upload_path_info['dirname'] . '/' . urlencode( $upload_path_info['filename'] ) . '*';
Linter warning here; variables shouldn't be aligned any more, but even if they are, comments reset alignment.
```suggestion
	$items[] = $upload_path_info['dirname'] . '/' . urlencode( $upload_path_info['filename'] ) . '*';
```

2024-02-08 07:39 UTC, merged